Repository IF-Trabalhos/SCCO, pull requests merged in 2023-06, with the labels that each got.

#42 Criação de uma rota privada
  src/App.js
  src/Rotas.js
  src/componentes/MenuLateral.js
  src/componentes/PaginaGenericaRelatorio.jsx
  src/componentes/relatorios/RelatorioClinica.jsx
  src/componentes/relatorios/RelatorioConvenio.jsx
  src/componentes/relatorios/RelatorioDentista.jsx
  src/componentes/relatorios/RelatorioPaciente.jsx
  src/pages/Inicio.jsx
  src/pages/Login.jsx
  src/pages/RelatorioInicial.jsx
  src/pages/agenda/Agenda.jsx
  src/pages/agenda/CadastroConsulta.jsx
  src/pages/convenio/CadastroConvenio.jsx
  src/pages/convenio/Convenio.jsx
  src/pages/dentista/CadastroDentista.jsx
  src/pages/dentista/Dentista.jsx
  src/pages/especialidade/CadastroEspecialidade.jsx
  src/pages/especialidade/Especialidade.jsx
  src/pages/financeiro/Financeiro.jsx
  src/pages/financeiro/convenio/CadastroFinanceiroConvenio.jsx
  src/pages/financeiro/convenio/FinanceiroConvenio.jsx
  src/pages/financeiro/mensal/CadastroFinanceiroMensal.jsx
  src/pages/financeiro/mensal/FinanceiroMensal.jsx
  src/pages/financeiro/paciente/CadastroFinanceiroPaciente.jsx
  src/pages/financeiro/paciente/FinanceiroPaciente.jsx
  src/pages/financeiro/recorrente/CadastroFinanceiroRecorrente.jsx
  src/pages/financeiro/recorrente/FinanceiroRecorrente.jsx
  src/pages/paciente/CadastroPaciente.jsx
  src/pages/paciente/Paciente.jsx
  src/pages/procedimento/CadastroProcedimento.jsx
  src/pages/procedimento/Procedimento.jsx
  src/pages/recepcionista/CadastroRecepcionista.jsx
  src/pages/recepcionista/Recepcionista.jsx
Labels: dependência

#40 Reformulação inicial do relatório
  package-lock.json
  package.json
  src/App.js
  src/componentes/PaginaGenericaRelatorio.jsx
  src/componentes/TelaInicialAgenda.css
  src/componentes/TelaInicialAgenda.jsx
  src/componentes/relatorios/RelatorioClinica.jsx
  src/componentes/relatorios/RelatorioConvenio.jsx
  src/componentes/relatorios/RelatorioDentista.jsx
  src/componentes/relatorios/RelatorioPaciente.jsx
  src/componentes/toastr.jsx
  src/pages/agenda/Agenda.jsx
  src/pages/agenda/CadastroConsulta.jsx
  src/pages/convenio/CadastroConvenio.jsx
  src/pages/convenio/Convenio.jsx
  src/pages/dentista/CadastroDentista.jsx
  src/pages/dentista/Dentista.jsx
  src/pages/especialidade/CadastroEspecialidade.jsx
  src/pages/especialidade/Especialidade.jsx
  src/pages/paciente/CadastroPaciente.jsx
  src/pages/paciente/Paciente.jsx
  src/pages/procedimento/CadastroProcedimento.jsx
  src/pages/procedimento/Procedimento.jsx
  src/pages/recepcionista/CadastroRecepcionista.jsx
  src/pages/recepcionista/Recepcionista.jsx
Labels: enriquecemento, melhoria

#43 Aprimorando css dos cadastros
  src/componentes/MenuLateral.js
  src/pages/convenio/CadastroConvenio.css
  src/pages/convenio/CadastroConvenio.jsx
  src/pages/dentista/CadastroDentista.css
  src/pages/dentista/CadastroDentista.jsx
  src/pages/paciente/CadastroPaciente.jsx
  src/pages/procedimento/Procedimento.css
  src/pages/recepcionista/CadastroRecepcionista.jsx
Labels: enriquecemento

#45 Criação do css para a página de login
  src/pages/Login.css
  src/pages/Login.jsx
  src/pages/dentista/CadastroDentista.css
  src/pages/dentista/CadastroDentista.jsx
Labels: melhoria
